### ISSUE TITLE
Problem with installation

### ISSUE THREAD

**Issue by quide** [varunsridharan/product-brands-for-woocommerce#3]
Hi,

I'm a rookie in wordpress/woocommerce.

I've just installed product-brands-for-woocommerce and got:
"Notice: Use of undefined constant PBF_WC_DB - assumed 'PBF_WC_DB' in /home/<we>/public_html/wp-content/plugins/product-brands-for-woocommerce/includes/functions.php on line 24"

---

using storefront 2.0.4
WooCommerce: 2.6.1
WC database: 2.6.1
WP: 4.5.3
PHP: 5.6.22
MySQL: 10.1.6

Active Plugins (18):
Dave's WordPress Live Search        by Dave Ross – 4.4.1
Debug Bar Console       by koopersmith – 0.3
Debug Bar       by wordpressdotorg – 0.8.4
Developer       by Automattic – 1.2.6
Jetpack by WordPress.com        by Automattic – 4.0.4
Log Deprecated Notices      by Andrew Nacin – 0.3
Log Viewer      by Markus Fischbacher – 14.05.04
Product Brands For WooCommerce      by Varun Sridharan – 0.4
Product Catalog     by Etoile Web Design – 3.8.7
WC Fields Factory       by Saravana Kumar K – 1.3.4
Widget Importer & Exporter      by Steven Gliebe – 1.3.1
Woocommerce CSV Import      by Allaerd Mensonides – 3.2.2
Booster for WooCommerce     by Algoritmika Ltd – 2.5.2
Woocommerce Order address Print     by Bhavik Patel – 2.0.2
WooCommerce     by WooThemes – 2.6.1
WordPress Importer      by wordpressdotorg – 0.6.1
Yoast SEO       by Team Yoast – 3.3.4
WPGlobus        by WPGlobus – 1.5.7

**Comment by varunsridharan** [comment]
@quide

Thanks for your report. i will take a look into it asap and fix it :)

**Comment by varunsridharan** [comment]
Hi,

The issue is fixed and updated in wordpress.org
